version: "3.9"

services:
  nginx:
    container_name: supermetrics-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4001:80"
    networks:
      - supermetrics

  backend:
    container_name: supermetrics-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    networks:
      - supermetrics

  frontend:
    container_name: supermetrics-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "4002:3000"
    networks:
      - supermetrics

networks:
  supermetrics:
    driver: bridge
