version: "3.9"

services:
  nginx:
    container_name: supermetrics-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4001:80"
    depends_on:
      - backend
    networks:
      - supermetrics

  backend:
    container_name: supermetrics-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - supermetrics_vendor:/app/vendor
      - ./backend:/app
    networks:
      - supermetrics

  frontend:
    container_name: supermetrics-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - supermetrics_nodemodules:/app/node_modules
      - ./frontend:/app
    ports:
      - "4002:3000"
    environment:
      - WDS_SOCKET_PORT=4002
    networks:
      - supermetrics

  database:
    container_name: supermetrics-database
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - supermetrics_db_data:/var/lib/mysql
    ports:
      - "4003:3306"
    security_opt:
      - seccomp:unconfined
    networks:
      - supermetrics

volumes:
  supermetrics_db_data:
  supermetrics_vendor:
  supermetrics_nodemodules:

networks:
  supermetrics:
    driver: bridge
