FROM php:8.0-fpm

WORKDIR /app/

#RUN composer install \
#    --ignore-platform-reqs \
#    --no-interaction \
#    --no-plugins \
#    --no-scripts \
#    --prefer-dist \

#COPY . /app


#RUN [ "php", "./index.php" ]
#RUN usermod -u 1000 www-data && groupmod -g 1000 www-data